[package]
name = "better_unwraps"
version = "0.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

[dependencies]
rewrite_unwraps = { path = "rewrite_unwraps/", optional = true }

[[example]]
name = "rewrite"
required-features = ["rewrite_unwraps"]
